@ModelStoreApi_HostAddress = http://localhost:5071

GET {{ModelStoreApi_HostAddress}}/modelstore/GetMetricNames

###

GET {{ModelStoreApi_HostAddress}}/modelstore/GetTags

###


GET {{ModelStoreApi_HostAddress}}/modelstore/GetTasks

###

GET {{ModelStoreApi_HostAddress}}/ModelStore/GetJobs

###

GET {{ModelStoreApi_HostAddress}}/modelstore/GetJobDefaults

###

@tag=animals
GET {{ModelStoreApi_HostAddress}}/modelstore/GetTrainingStats?tag={{tag}}

###
