@ModelStoreApi_HostAddress = http://localhost:5071

GET {{ModelStoreApi_HostAddress}}/modelstore/GetMetricNames

###

GET {{ModelStoreApi_HostAddress}}/modelstore/GetTags

###


GET {{ModelStoreApi_HostAddress}}/modelstore/GetTasks

###

POST {{ModelStoreApi_HostAddress}}/modelstore/InsertJob
Content-Type: application/json

{
  "task": "convnet_task.ConvNetTask",
  "args": [[128, 128], [16, 32], [64, 10]],
  "kwargs": { "conv_dropout": 0.1, "fc_dropout": 0.1, "tag": "animals", "image_root": "animals/images" }
}

###

GET {{ModelStoreApi_HostAddress}}/ModelStore/GetJobs

###

GET {{ModelStoreApi_HostAddress}}/modelstore/GetJobDefaults

###

@tag=animals
GET {{ModelStoreApi_HostAddress}}/modelstore/GetTrainingStats?tag={{tag}}

###
